# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2'

volumes:
  suricata-config:
  suricata-rules:
  #suricata-log:

services:
# Suricata service
  suricata:
    container_name: suricata
    image: suricata:latest
    #Obtiene el valor desde el ENV de docker-compose
    command: "${SURICATA_ARGS}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Obtiene el valor desde el ENV de docker-compose
        TZ: "${TZ}"
    network_mode: "host"
    environment:
      # Obtiene el valor desde el ENV de docker-compose
      TZ:
      SURICATA_ARGS:
    volumes:
      # Volume mode
      - 'suricata-config:/etc/suricata'
      - 'suricata-rules:/var/lib/suricata'
      #- 'suricata-log/var/log/suricata'
      # Mount bind mode
      #- '/opt/suricata/config/:/etc/suricata'
      #- '/opt/suricata/rules:/var/lib/suricata'
      - '/var/log/docker/suricata:/var/log/suricata'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    restart: unless-stopped