# Imagen base
FROM ubuntu:latest

# Al ejecutar todo en una única línea RUN, evitamos que se generen images con las dependencias transitorias
# Dependencias del sistema
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:oisf/suricata-stable && \
    apt update \
    apt install suricata \
    apt remove --purge software-properties-common \
    apt autoremove \
    apt autoclean

# Configuración
