# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2'

services:
# Suricata service
  suricata:
    container_name: suricata
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    enviroment:
      TZ: "Europe/Madrid"
    volumes:
      # Volume mode
      - 'suricata-config:/etc/suricata'
      - 'suricata-rules:/var/lib/suricata'
      #- 'suricata-log/var/log/suricata'
      # Mount bind mode
      #- '/opt/suricata/config/:/etc/suricata'
      #- '/opt/suricata/rules:/var/lib/suricata'
      - '/var/log/docker/suricata:/var/log/suricata'
     cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
     restart: unless-stopped